# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6818ebccc6d16838fb90fcdf3619682ed7a81674e2f5eca61e4ae6a69754b2fb39273a7145368f9b0c0d3b55280bbe95333ba3801ef1b26322fcf02519c003e

test:
  secret_key_base: b994053b7f2ad71bc1d9da34da2c34bde04b89af64e4bb6c95ad8e758dbabe710eefb375c8952de6db5ed15c591364a4a880a31468a8e3da9c7ca6537e7ad6fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
